basePath: /api
definitions:
  models.BinaryOperationRequest:
    properties:
      a:
        type: number
      b:
        type: number
    type: object
  models.CalculationResponse:
    properties:
      result:
        type: number
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.UnaryOperationRequest:
    properties:
      value:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a calculator server implementing a Hexagonal Architecture.
  title: Calculator HTTP API
  version: "1.0"
paths:
  /add:
    post:
      consumes:
      - application/json
      description: Adds operand A to operand B.
      parameters:
      - description: Operands
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BinaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Error like Invalid JSON, NaN/Inf, or Overflow
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Addition
      tags:
      - Binary Operations
  /divide:
    post:
      consumes:
      - application/json
      description: Divides operand A by operand B. Returns a 400 Error in case of
        division by zero.
      parameters:
      - description: Operands
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BinaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Division
      tags:
      - Binary Operations
  /exponentiate:
    post:
      consumes:
      - application/json
      description: Raises base to the power of exponent.
      parameters:
      - description: Base and exponent
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BinaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Error like Invalid JSON, NaN/Inf, or Overflow
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Exponentiation
      tags:
      - Binary Operations
  /multiply:
    post:
      consumes:
      - application/json
      description: Multiplies operand A by operand B.
      parameters:
      - description: Operands
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BinaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Multiplication
      tags:
      - Binary Operations
  /negate:
    post:
      consumes:
      - application/json
      description: Returns the negative value of the input.
      parameters:
      - description: Single operand
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UnaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Negation (Sign Change)
      tags:
      - Unary Operations
  /percentage:
    post:
      consumes:
      - application/json
      description: Returns the percentage of the given value (value / 100).
      parameters:
      - description: Single operand
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UnaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Percentage
      tags:
      - Unary Operations
  /squareroot:
    post:
      consumes:
      - application/json
      description: Returns the square root of the given value. Returns a 400 Error
        for negative values.
      parameters:
      - description: Single operand
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UnaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Square Root
      tags:
      - Unary Operations
  /subtract:
    post:
      consumes:
      - application/json
      description: Subtracts operand B from operand A.
      parameters:
      - description: Operands
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BinaryOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Calculation result
          schema:
            $ref: '#/definitions/models.CalculationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Subtraction
      tags:
      - Binary Operations
swagger: "2.0"
